### ISSUE TITLE
testsetv2 dataset

### ISSUE THREAD

**Issue by 3202336152** [lhc1224/Cross-View-AG#2]
hello, thank you for providing your work.I would like to ask, can you post the link to the testsetv2 dataset in the description?

**Comment by lhc1224** [comment]
The dataset will be released later.

**Comment by jdiazram** [comment]
Hi, excellent work.
I have the same question because the dataset testsetv2 link is not available.
Thx

**Comment by lhc1224** [comment]
I've uploaded it to this link: https://pan.baidu.com/s/15OKk1KVfhjkoVAYD2o7Mpg?pwd=kaw6
