### ISSUE TITLE
No such file or direcctory: ' Seen_gt.t7'

### ISSUE THREAD

**Issue by ccmCCMfk** [lhc1224/Cross-View-AG#4]
Thanks for your great work.Before I try to train a model,I run  process_gt.py to generate Unseen_gt.t7，and I replaced Unseen with Seen to generate Seen_gt.t7.
gt_root="dataset/AGD20K/Seen/testset/GT/"
torch.save(dict_1,"Seen_gt.t7")
but when I train a model,it didn't work,do you know what's the problem?()
Train begining!
train 	 Epoch:[1/35]	step:[50/1254] 	 cls_loss: 7.113	 dist_loss: 1.722	 exo_acc: 22.75% 	 ego_acc: 21.88%
train 	 Epoch:[1/35]	step:[100/1254] 	 cls_loss: 4.066	 dist_loss: 1.937	 exo_acc: 30.00% 	 ego_acc: 28.69%
train 	 Epoch:[1/35]	step:[150/1254] 	 cls_loss: 5.073	 dist_loss: 2.349	 exo_acc: 35.25% 	 ego_acc: 32.38%
train 	 Epoch:[1/35]	step:[200/1254] 	 cls_loss: 3.748	 dist_loss: 2.042	 exo_acc: 37.56% 	 ego_acc: 34.66%
train 	 Epoch:[1/35]	step:[250/1254] 	 cls_loss: 2.537	 dist_loss: 1.704	 exo_acc: 39.25% 	 ego_acc: 35.85%
train 	 Epoch:[1/35]	step:[300/1254] 	 cls_loss: 4.081	 dist_loss: 1.695	 exo_acc: 40.94% 	 ego_acc: 37.40%
train 	 Epoch:[1/35]	step:[350/1254] 	 cls_loss: 3.147	 dist_loss: 1.032	 exo_acc: 42.61% 	 ego_acc: 38.57%
train 	 Epoch:[1/35]	step:[400/1254] 	 cls_loss: 2.145	 dist_loss: 1.638	 exo_acc: 43.98% 	 ego_acc: 39.78%
train 	 Epoch:[1/35]	step:[450/1254] 	 cls_loss: 5.803	 dist_loss: 1.145	 exo_acc: 45.15% 	 ego_acc: 40.65%
train 	 Epoch:[1/35]	step:[500/1254] 	 cls_loss: 3.255	 dist_loss: 1.598	 exo_acc: 46.45% 	 ego_acc: 41.49%
train 	 Epoch:[1/35]	step:[550/1254] 	 cls_loss: 1.971	 dist_loss: 1.693	 exo_acc: 47.32% 	 ego_acc: 42.10%
train 	 Epoch:[1/35]	step:[600/1254] 	 cls_loss: 1.749	 dist_loss: 1.391	 exo_acc: 48.07% 	 ego_acc: 42.68%
train 	 Epoch:[1/35]	step:[650/1254] 	 cls_loss: 2.975	 dist_loss: 1.919	 exo_acc: 48.81% 	 ego_acc: 43.12%
train 	 Epoch:[1/35]	step:[700/1254] 	 cls_loss: 2.258	 dist_loss: 1.279	 exo_acc: 49.47% 	 ego_acc: 43.54%
train 	 Epoch:[1/35]	step:[750/1254] 	 cls_loss: 2.977	 dist_loss: 1.647	 exo_acc: 49.87% 	 ego_acc: 43.95%
train 	 Epoch:[1/35]	step:[800/1254] 	 cls_loss: 2.014	 dist_loss: 1.469	 exo_acc: 50.30% 	 ego_acc: 44.44%
train 	 Epoch:[1/35]	step:[850/1254] 	 cls_loss: 2.583	 dist_loss: 1.326	 exo_acc: 50.64% 	 ego_acc: 44.65%
train 	 Epoch:[1/35]	step:[900/1254] 	 cls_loss: 2.099	 dist_loss: 1.432	 exo_acc: 51.14% 	 ego_acc: 45.11%
train 	 Epoch:[1/35]	step:[950/1254] 	 cls_loss: 2.247	 dist_loss: 1.262	 exo_acc: 51.71% 	 ego_acc: 45.61%
train 	 Epoch:[1/35]	step:[1000/1254] 	 cls_loss: 3.252	 dist_loss: 1.017	 exo_acc: 52.01% 	 ego_acc: 45.85%
train 	 Epoch:[1/35]	step:[1050/1254] 	 cls_loss: 1.915	 dist_loss: 1.219	 exo_acc: 52.30% 	 ego_acc: 46.11%
train 	 Epoch:[1/35]	step:[1100/1254] 	 cls_loss: 2.588	 dist_loss: 1.692	 exo_acc: 52.57% 	 ego_acc: 46.27%
train 	 Epoch:[1/35]	step:[1150/1254] 	 cls_loss: 2.674	 dist_loss: 1.557	 exo_acc: 52.88% 	 ego_acc: 46.49%
train 	 Epoch:[1/35]	step:[1200/1254] 	 cls_loss: 2.227	 dist_loss: 1.067	 exo_acc: 53.17% 	 ego_acc: 46.79%
train 	 Epoch:[1/35]	step:[1250/1254] 	 cls_loss: 2.756	 dist_loss: 1.217	 exo_acc: 53.41% 	 ego_acc: 47.00%
Traceback (most recent call last):
  File "train.py", line 221, in <module>
    masks = torch.load(args.divide+"_gt.t7")
  File "/home/chenchangmao/anaconda3/envs/affordance/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/chenchangmao/anaconda3/envs/affordance/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/chenchangmao/anaconda3/envs/affordance/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'Seen_gt.t7'

**Comment by lhc1224** [comment]
Is the path generated by “Seen_gt.t7” correct?

**Comment by ccmCCMfk** [comment]
I forgot something,it works right now,thanks for your reply.
