### ISSUE TITLE
TypeError: MODEL() got an unexpected keyword argument 'align_channels'

### ISSUE THREAD

**Issue by ccmCCMfk** [lhc1224/Cross-View-AG#5]
when I run test.py,a typeError came out,and I found that in model.py fucion MODEL is:
def MODEL(args, num_classes=36,
           align_w=0.2, distil_w=0.1,
          cls_w=1, pretrained=True,n=3,D=512):
but in test.py,
model = MODEL(args, num_classes=len(aff_list),
                  align_channels=256, align_w=0.5, distil_w=0.5,
                  cls_w=1, pretrained=False).cuda()
is the patameter align_channels irrelevant? shall we just delete it?
It had a result on pycharm IDE ,but not work on the server unless I delete that parameter.
By the way,can I ask for the code about plotting,I'm also a student from department of automation,ustc.

**Comment by ccmCCMfk** [comment]
I saw some information in the extension,but do not know how to utilize it.

**Comment by lhc1224** [comment]
You can email me and add me on WeChat
