### ISSUE TITLE
The difference between result of test and gt

### ISSUE THREAD

**Issue by ccmCCMfk** [lhc1224/Cross-View-AG#6]
This is my result of test.py:
kld = 1.521207194771439
sim = 0.34196439919030536
nss = 0.9306758723494548
 but when I try to visualize the affordance region in test.py,it has a big difference contrast to the ground truth region.
result:
![swing_baseball_bat_baseball_bat_000452 png](https://github.com/lhc1224/Cross-View-AG/assets/86772637/e08af9a3-6100-47a5-859d-ae2cc1b2376a)
ground truth:
![swing_baseball_bat_baseball_bat_000452 pnggt](https://github.com/lhc1224/Cross-View-AG/assets/86772637/35954e0a-9c61-430e-9b07-62cb4e583cdc)
result:
![swing_baseball_bat_baseball_bat_000595 png](https://github.com/lhc1224/Cross-View-AG/assets/86772637/95bd5916-15c3-4214-9000-3edb257996bb)
ground truth:
![swing_baseball_bat_baseball_bat_000595 pnggt](https://github.com/lhc1224/Cross-View-AG/assets/86772637/ad2b2ae1-8685-41dd-833a-29f5b4dfb337)

**Comment by lhc1224** [comment]
The task is a weakly supervised setting and does not have accurate pixel-level labelling as supervision, thus some examples show relative location that is not accurate enough.
