### ISSUE TITLE
Camera Intrinsic parameters

### ISSUE THREAD

**Issue by charlottejruby** [lhc1224/Cross-View-AG#7]
Thank you for your great work.

Thanks to your impressive work, I'm currently working on converting the images from the AGD20k dataset into depth maps and subsequently into point clouds. Would it be possible to obtain the camera's intrinsic parameter  (focal length in the x direction and y direction) for the AGD20k dataset? Also can I know the depth scale and depth truncation of AGD 20k?

Thank you!

**Comment by lhc1224** [comment]
Sorry, all this data is taken from the web as well as from different datasets, and it may be more difficult to get intrinsic parameter as well as depth information. It may be necessary to rely on other models for estimation. Or consider trying to replace the egocentric image with your own captured data

**Comment by charlottejruby** [comment]
Thank you for replying!

I will try to capture my own image.

Thank you!
